### PR TITLE
Fix: Update to ES6 syntax (fixes #40)

### LINKED ISSUE #40: Update to ES6 syntax
### Subject of the enhancement
Code should be updated to ES6 syntax.

### PR DESCRIPTION
**Pull request by swashbuck**
Fix #40 

### Fix
* Updates code to ES6 syntax 
* Flesh out readme
* Fix typo in PR template

### CODE REVIEW

File: js/adapt-pageIncompletePrompt.js [hunk 1]
```diff
@@ -1,183 +1,174 @@
...
+    this.listenTo(Adapt, {
+      'app:languageChanged': this.onLanguageChanging,
+      'pageView:ready': this.onPageViewReady,
+      'pageIncompletePrompt:leavePage': this.onLeavePage,
+      'pageIncompletePrompt:cancel': this.onLeaveCancel,
+      'router:navigate': this.onRouterNavigate
+    });
+
+    this.listenToOnce(Adapt, 'app:dataLoaded', function() {
+      this.listenTo(Adapt, 'accessibility:toggle', this.onAccessibilityToggle);
```
Comment (oliverfoster) [inline js/adapt-pageIncompletePrompt.js:31]: It's odd that this is attached only after `app:dataLoaded`. 
I don't think `accessibility:toggle` exists now, as a11y is on all of the time and we don't now have a button to toggle its behaviour? All of this can be removed.

Old code: https://github.com/search?q=repo%3Aadaptlearning%2Fadapt-contrib-core+accessibility%3Atoggle&type=commits

File: js/adapt-pageIncompletePrompt.js [hunk 2]
```diff
@@ -1,183 +1,174 @@
...
+  /**
+   * Suppresses the prompt if the user changes language whilst in a page, then re-enables
+   * it once the language has been changed and we have navigated back to a page.
+   */
+  onLanguageChanging() {
+    this.isChangingLanguage = true;
+
+    Adapt.once('router:page', function() {
+      this.isChangingLanguage = false;
+    }.bind(this));
```
Comment (oliverfoster) [inline js/adapt-pageIncompletePrompt.js:44]:
```suggestion
    Adapt.once('router:page', () => {
      this.isChangingLanguage = false;
    });
```

File: js/adapt-pageIncompletePrompt.js [hunk 3]
```diff
@@ -1,183 +1,174 @@
...
+      const model = data.findById(id);
+      const parent = model && model.findAncestor('contentObjects');
+      if (parent && (parent.get('_id') === this.pageModel.get('_id'))) return;
     }
 
-  });
+    if (this._ignoreAccessibilityNavigation) {
+      this._ignoreAccessibilityNavigation = false;
+      return;
+    }
```
Comment (oliverfoster) [inline js/adapt-pageIncompletePrompt.js:100]: Remove as per previous comment

File: js/adapt-pageIncompletePrompt.js [hunk 4]
```diff
@@ -1,183 +1,174 @@
...
+  onAccessibilityToggle() {
+    if (device.touch) {
+      // Ignore toggle. Accessibility is always on for touch devices
+      this._ignoreAccessibilityNavigation = false;
+      return;
+    }
+
+    // Skip renavigate for accessibility on desktop
+    this._ignoreAccessibilityNavigation = true;
+  }
```
Comment (oliverfoster) [inline js/adapt-pageIncompletePrompt.js:115]: Remove as per previous comment

File: js/adapt-pageIncompletePrompt.js [hunk 5]
```diff
@@ -1,183 +1,174 @@
...
+    if (pipConfig && pipConfig._buttons) {
+      promptObject.title = pipConfig.title;
+      promptObject.body = pipConfig.message;
+      promptObject._classes = pipConfig._classes;
+      promptObject._prompts[0].promptText = pipConfig._buttons.yes;
+      promptObject._prompts[1].promptText = pipConfig._buttons.no;
+    }
+
+    this.listenToOnce(Adapt, 'notify:cancelled', this.onLeaveCancel);
+    Adapt.trigger('notify:prompt', promptObject);
```
Comment (oliverfoster) [inline js/adapt-pageIncompletePrompt.js:144]: notify.prompt or notify.create

**Review by oliverfoster — DISMISSED** [review]
initial look

**Review by oliverfoster — APPROVED** [review]
